[package]
name = "unix-tty"
version = "0.3.2"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Unix TTY API"
license = "MIT OR Apache-2.0"

[dependencies]
i-o = "0.4"
libc = { version = "0.2", default-features = false }
null-terminated = "0.3"
system-call = "0.1"
unix = "0.6.5"
