[package]
name = "unix-tty"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Unix TTY API"
license = "MIT OR Apache-2.0"

[dependencies]
i-o = "0.3"
libc = { version = "0.2", default-features = false }
null-terminated = "0.2.6"
syscall = "0.2"
unix = "0.3.1"
